// Generated by png2c [(c) Oleg Vaskevich 2013]

#ifndef _example_H_
#define _example_H_

extern const unsigned int example_width;
extern const unsigned int example_height;
extern const int example_size;
extern const unsigned short example[];

#endif

